GET http://localhost:3000/clientes

###
POST http://localhost:3000/clientes
Content-Type: application/json

{
    "nome": "Helder",
    "email": "helderjfl@gmail.com"
    "cpf": "1111111111"
    "data_nasc": "1990-02-02",
}

###
GET http://localhost:3000/clientes/4
